FROM opensuse/tumbleweed:latest

RUN zypper --non-interactive refresh \
    && zypper --non-interactive install make wget perl coreutils

WORKDIR /tmp
RUN wget -O - https://github.com/bahmanm/bmakelib/releases/download/v0.7.0/bmakelib-0.7.0.tar.gz | tar zxf - \
    && cd bmakelib-0.7.0 \
    && PREFIX=/usr/local make install

VOLUME /project
WORKDIR /project
ENTRYPOINT ["/usr/bin/make"]
