---
version: 2.1

####################################################################################################

executors:
  ubuntu2204:
    resource_class: medium
    machine:
      image: ubuntu-2204:current

####################################################################################################

commands:
  ubuntu_setup:
    description: >-
      Setup the required packages for the build process.
    steps:
      - run:
          name: Update package index
          command: >-
            sudo apt-get update
      - run:
          name: Install Make 4.4
          command: >-
            pushd /tmp
            && wget -O - https://ftp.gnu.org/gnu/make/make-4.4.1.tar.gz | tar -zxf -
            && pushd make-4.4.1
            && ./configure --prefix=/usr/local
            && sudo make install
            && popd
            && popd
      - run:
          name: Install bmakelib
          command: >-
            pushd /tmp
            && wget https://github.com/bahmanm/bmakelib/releases/download/v0.7.0/bmakelib_0.7.0-1_all.deb
            && sudo dpkg -i bmakelib_0.7.0-1_all.deb
            && popd


####################################################################################################

jobs:

  test:
    executor: ubuntu2204
    working_directory: ~/bdockerimg
    steps:
      - ubuntu_setup
      - checkout
      - run:
          name: Run tests
          command: >-
            make test

  build:
    executor: ubuntu2204
    working_directory: ~/bdockerimg
    steps:
      - ubuntu_setup
      - checkout
      - run:
          name: Build the images
          command: >-
            make build

  publish:
    executor: ubuntu2204
    working_directory: ~/bdockerimg
    steps:
      - ubuntu_setup
      - checkout
      - run:
          name: Publish the images to Docker Hub
          command: >-
            make publish

####################################################################################################

workflows:
  test:
    jobs:
      - test
      - build
      - publish
