---
version: 2.1

####################################################################################################

executors:
  ubuntu2204:
    resource_class: medium
    machine:
      image: ubuntu-2204:current
      docker_layer_caching: true

####################################################################################################

commands:
  ubuntu_setup:
    description: >-
      Setup the required packages for the build process.
    steps:
      - run:
          name: Install Make 4.4
          command: >-
            pushd /tmp
            && wget -O - https://ftp.gnu.org/gnu/make/make-4.4.1.tar.gz | tar -zxf -
            && pushd make-4.4.1
            && ./configure --prefix=/usr/local
            && sudo make install
            && popd
            && popd
      - run:
          name: Install bmakelib
          command: >-
            pushd /tmp
            && wget https://github.com/bahmanm/bmakelib/releases/download/v0.7.0/bmakelib_0.7.0-1_all.deb
            && sudo dpkg -i bmakelib_0.7.0-1_all.deb
            && popd


####################################################################################################

jobs:

  build:
    executor: ubuntu2204
    working_directory: ~/bdockerimg
    steps:
      - ubuntu_setup
      - checkout
      - run:
          name: Build the images
          command: >-
            make build

  test:
    executor: ubuntu2204
    working_directory: ~/bdockerimg
    steps:
      - ubuntu_setup
      - checkout
      - run:
          name: Run tests
          command: >-
            make test

  publish:
    executor: ubuntu2204
    working_directory: ~/bdockerimg
    steps:
      - ubuntu_setup
      - checkout
      - run:
          name: Publish the images to Docker Hub
          command: >-
            echo ${DOCKERHUB_TOKEN} | docker login --username ${DOCKERHUB_USER} --password-stdin
            && make publish

  publish_fusions:
    executor: ubuntu2204
    working_directory: ~/bdockerimg
    steps:
      - ubuntu_setup
      - checkout
      - run:
          name: Build and publish the fusions
          command: >-
            make fusion.all.build fusion.all.publish

####################################################################################################

workflows:
  test:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - main
      - test:
          requires:
            - build
          filters:
            branches:
              ignore:
                - main

  publish:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - test:
          requires:
            - build
          filters:
            branches:
              only:
                - main
      - publish:
          requires:
            - test
          filters:
            branches:
              only:
                - main

      - publish_fusions:
          requires:
            - publish
          filters:
            branches:
              only:
                - main

  weekly:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish:
          requires:
            - test
      - publish_fusions:
          requires:
            - publish
    triggers:
      - schedule:
          cron: "0 18 * * 1"
          filters:
            branches:
              only:
                - main
