---
version: 2.1

####################################################################################################

executors:
  ubuntu2204:
    resource_class: medium
    machine:
      image: ubuntu-2204:current

####################################################################################################

jobs:

  test:
    executor: ubuntu2204
    steps:
      - checkout
      - run:
          name: Run tests
          command: >-
            make test

  build:
    executor: ubuntu2204
    steps:
      - checkout
      - run:
          name: Build the images
          command: >-
            make build

  publish:
    executor: ubuntu2204
    steps:
      - checkout
      - run:
          name: Publish the images to Docker Hub
          command: >-
            make publish

####################################################################################################

workflows:
  test:
    jobs:
      - test
      - build
      - publish
