FROM ubuntu:24.04

RUN apt-get update \
    && apt-get install -y zip unzip wget curl \
    && rm -rf /var/lib/{apt,dpkg,cache,log}/

RUN wget --quiet -O - https://get.sdkman.io | bash

COPY --chmod=777 entrypoint /entrypoint

VOLUME /project
WORKDIR /project
ENTRYPOINT ["/entrypoint"]
